<?php
/**
 * Blog phase: article index records. Bodies live in /blog/<slug>/index.php.
 * `service` is null on purpose; the link pass sets it from the LINKPASS comments.
 */

declare(strict_types=1);

return [
    [
        'slug'        => 'sueldo-de-un-programador-en-paraguay',
        'title'       => 'Sueldo de un programador en Paraguay: qué lo define y rangos orientativos',
        'seoTitle'    => 'Sueldo de un programador en Paraguay',
        'description' => 'Qué determina el sueldo de un programador en Paraguay: seniority, tecnología, inglés y modalidad. Rangos orientativos, sin encuestas inventadas.',
        'date'        => '2026-08-01',
        'updated'     => null,
        'tags'        => ['Carrera', 'Programación', 'Sueldos'],
        'service'     => 'programadores',
    ],
    [
        'slug'        => 'como-ser-desarrollador-full-stack',
        'title'       => 'Cómo ser desarrollador full stack: ruta de aprendizaje práctica',
        'seoTitle'    => 'Cómo ser desarrollador full stack',
        'description' => 'Ruta práctica para ser desarrollador full stack: frontend, backend, bases de datos, despliegue y proyectos que demuestran lo aprendido ante un empleador.',
        'date'        => '2026-08-04',
        'updated'     => null,
        'tags'        => ['Carrera', 'Programación', 'Full stack'],
        'service'     => 'desarrollo-de-software',
    ],
    [
        'slug'        => 'desarrollador-junior-sin-experiencia',
        'title'       => 'Desarrollador junior sin experiencia: cómo conseguir el primer empleo',
        'seoTitle'    => 'Desarrollador junior sin experiencia',
        'description' => 'Cómo conseguir su primer empleo como desarrollador junior sin experiencia en Paraguay: portafolio, currículum, entrevistas técnicas y dónde postularse.',
        'date'        => '2026-08-07',
        'updated'     => null,
        'tags'        => ['Carrera', 'Programación', 'Primer empleo'],
        'service'     => 'programadores',
    ],
    [
        'slug'        => 'pasantias-de-programacion-en-paraguay',
        'title'       => 'Pasantías de programación en Paraguay: cómo encontrarlas y aprovecharlas',
        'seoTitle'    => 'Pasantías de programación en Paraguay',
        'description' => 'Guía sobre pasantías de programación en Paraguay: dónde buscarlas, qué pedir antes de aceptar, cómo aprovecharlas y cómo convertirlas en un empleo.',
        'date'        => '2026-08-10',
        'updated'     => null,
        'tags'        => ['Carrera', 'Programación', 'Pasantías'],
        'service'     => 'programadores',
    ],
    [
        'slug'        => 'ingenieria-de-software-en-paraguay',
        'title'       => 'Ingeniería de software en Paraguay: carreras, alternativas y cómo elegir',
        'seoTitle'    => 'Ingeniería de software en Paraguay',
        'description' => 'Panorama general de la ingeniería de software en Paraguay: carreras en universidades como UNA, UCA y UAA, alternativas técnicas y cómo elegir su camino.',
        'date'        => '2026-08-13',
        'updated'     => null,
        'tags'        => ['Carrera', 'Programación', 'Formación'],
        'service'     => 'desarrollo-de-software',
    ],
    [
        'slug'        => 'cursos-de-programacion-recomendados',
        'title'       => 'Cursos de programación recomendados: cómo elegir uno que sirva',
        'seoTitle'    => 'Cursos de programación recomendados',
        'description' => 'Criterios para elegir cursos de programación recomendados: gratuitos, pagos, presenciales y en línea, y cómo convertir lo aprendido en un portafolio real.',
        'date'        => '2026-08-16',
        'updated'     => null,
        'tags'        => ['Carrera', 'Programación', 'Formación'],
        'service'     => 'programadores',
    ],
    [
        'slug'        => 'trabajo-remoto-para-programadores-paraguayos',
        'title'       => 'Trabajo remoto para programadores paraguayos: cómo prepararse',
        'seoTitle'    => 'Trabajo remoto para programadores en PY',
        'description' => 'Qué necesita un programador paraguayo para trabajar en remoto: habilidades, inglés, cobros desde el exterior, facturación y cómo evitar ofertas dudosas.',
        'date'        => '2026-08-19',
        'updated'     => null,
        'tags'        => ['Carrera', 'Programación', 'Trabajo remoto'],
        'service'     => 'programadores',
    ],
    [
        'slug'        => 'software-a-medida-vs-software-enlatado',
        'title'       => 'Software a medida vs software enlatado: cómo decidir en su empresa',
        'seoTitle'    => 'Software a medida vs software enlatado',
        'description' => 'Software a medida o enlatado: costo, tiempo, adaptación, dependencia del proveedor y criterios para decidir en una empresa paraguaya.',
        'date'        => '2026-08-22',
        'updated'     => null,
        'tags'        => ['Empresas', 'Software', 'Decisiones'],
        'service'     => 'desarrollo-de-software',
    ],
    [
        'slug'        => 'como-elegir-una-empresa-de-desarrollo-de-software',
        'title'       => 'Cómo elegir una empresa de desarrollo de software sin equivocarse',
        'seoTitle'    => 'Cómo elegir empresa de desarrollo',
        'description' => 'Cómo elegir una empresa de desarrollo de software en Paraguay: propuesta, proceso, propiedad del código, soporte y señales de alerta.',
        'date'        => '2026-08-25',
        'updated'     => null,
        'tags'        => ['Empresas', 'Software', 'Proveedores'],
        'service'     => 'desarrollo-de-software',
    ],
    [
        'slug'        => 'wordpress-o-sitio-a-medida',
        'title'       => 'WordPress o sitio a medida: cuál conviene para su empresa',
        'seoTitle'    => 'WordPress o sitio a medida',
        'description' => 'WordPress o sitio a medida: costo, velocidad, mantenimiento, seguridad y flexibilidad para decidir según el objetivo de su web.',
        'date'        => '2026-08-28',
        'updated'     => null,
        'tags'        => ['Empresas', 'Sitios web', 'WordPress'],
        'service'     => 'wordpress',
    ],
    [
        'slug'        => 'whatsapp-para-vender-mas',
        'title'       => 'WhatsApp para vender más: cómo ordenar la atención y no perder clientes',
        'seoTitle'    => 'WhatsApp para vender más',
        'description' => 'Cómo usar WhatsApp para vender más en Paraguay: catálogo, respuestas rápidas, API oficial, integración con CRM y métricas para no perder consultas.',
        'date'        => '2026-08-31',
        'updated'     => null,
        'tags'        => ['Empresas', 'WhatsApp', 'Ventas'],
        'service'     => 'whatsapp-business-api',
    ],
    [
        'slug'        => 'facturacion-electronica-obligatoria-que-cambia-para-su-empresa',
        'title'       => 'Facturación electrónica obligatoria: qué cambia para su empresa',
        'seoTitle'    => 'Facturación electrónica obligatoria',
        'description' => 'Qué cambia con la facturación electrónica obligatoria en Paraguay: SIFEN, documentos electrónicos, KuDE, sistemas propios y pasos para prepararse a tiempo.',
        'date'        => '2026-09-03',
        'updated'     => null,
        'tags'        => ['Empresas', 'Facturación electrónica', 'SIFEN'],
        'service'     => 'facturacion-electronica-sifen',
    ],
    [
        'slug'        => 'como-cobrar-online-en-paraguay',
        'title'       => 'Cómo cobrar online en Paraguay: opciones para su empresa',
        'seoTitle'    => 'Cómo cobrar online en Paraguay',
        'description' => 'Cómo cobrar online en Paraguay: pasarelas, billeteras, transferencias, links de pago y QR, y cómo integrarlos con su sitio y su facturación.',
        'date'        => '2026-09-06',
        'updated'     => null,
        'tags'        => ['Empresas', 'Pagos', 'Comercio electrónico'],
        'service'     => 'integracion-pagos',
    ],
    [
        'slug'        => 'erp-para-pymes-paraguayas',
        'title'       => 'ERP para pymes paraguayas: qué es, cuándo conviene y cómo elegir',
        'seoTitle'    => 'ERP para pymes paraguayas',
        'description' => 'ERP para pymes paraguayas: cuándo conviene, qué módulos priorizar, cómo elegir entre opciones e implementarlo por etapas sin frenar la operación.',
        'date'        => '2026-09-09',
        'updated'     => null,
        'tags'        => ['Empresas', 'ERP', 'Gestión'],
        'service'     => 'sistemas-erp',
    ],
    [
        'slug'        => 'crm-para-pymes-como-empezar',
        'title'       => 'CRM para pymes: cómo empezar sin complicarse',
        'seoTitle'    => 'CRM para pymes: cómo empezar',
        'description' => 'Cómo empezar con un CRM en una pyme paraguaya: qué registrar, cómo armar el embudo de ventas, integración con WhatsApp y errores comunes en la adopción.',
        'date'        => '2026-09-12',
        'updated'     => null,
        'tags'        => ['Empresas', 'CRM', 'Ventas'],
        'service'     => 'crm',
    ],
    [
        'slug'        => 'que-es-una-api-explicado-para-empresarios',
        'title'       => 'Qué es una API, explicado para empresarios',
        'seoTitle'    => 'Qué es una API, para empresarios',
        'description' => 'Qué es una API explicado sin tecnicismos: cómo conecta sistemas, ejemplos en Paraguay con pagos, facturación y WhatsApp, y qué preguntar antes de integrar.',
        'date'        => '2026-09-15',
        'updated'     => null,
        'tags'        => ['Empresas', 'Integraciones', 'API'],
        'service'     => 'desarrollo-de-software',
    ],
    [
        'slug'        => 'por-que-su-pagina-web-no-aparece-en-google',
        'title'       => 'Por qué su página web no aparece en Google y cómo solucionarlo',
        'seoTitle'    => 'Por qué su web no aparece en Google',
        'description' => 'Por qué su página web no aparece en Google: indexación, bloqueos técnicos, contenido débil, competencia y perfil local, con pasos para corregirlo.',
        'date'        => '2026-09-18',
        'updated'     => null,
        'tags'        => ['Empresas', 'SEO', 'Sitios web'],
        'service'     => 'seo',
    ],
    [
        'slug'        => 'cuanto-tarda-desarrollar-un-software',
        'title'       => 'Cuánto tarda desarrollar un software y qué lo acelera o demora',
        'seoTitle'    => 'Cuánto tarda desarrollar un software',
        'description' => 'Cuánto tarda desarrollar un software a medida: etapas, factores que alargan los plazos, cómo estimar con realismo y cómo acortar tiempos.',
        'date'        => '2026-09-20',
        'updated'     => null,
        'tags'        => ['Empresas', 'Software', 'Planificación'],
        'service'     => 'desarrollo-de-software',
    ],
    [
        'slug'        => 'mantener-o-rehacer-su-sitio-web',
        'title'       => 'Mantener o rehacer su sitio web: cómo tomar la decisión',
        'seoTitle'    => 'Mantener o rehacer su sitio web',
        'description' => 'Mantener o rehacer su sitio web: estado técnico, contenido, velocidad, costos de mantenimiento y cómo migrar sin perder visitas de Google.',
        'date'        => '2026-09-22',
        'updated'     => null,
        'tags'        => ['Empresas', 'Sitios web', 'Mantenimiento'],
        'service'     => 'paginas-web',
    ],
    [
        'slug'        => 'ia-en-empresas-paraguayas-casos-practicos',
        'title'       => 'IA en empresas paraguayas: casos prácticos que se pueden construir',
        'seoTitle'    => 'IA en empresas paraguayas: casos',
        'description' => 'Casos prácticos de IA en empresas paraguayas: atención por WhatsApp, lectura de documentos, clasificación de consultas y reportes.',
        'date'        => '2026-09-24',
        'updated'     => null,
        'tags'        => ['Empresas', 'Inteligencia artificial', 'Automatización'],
        'service'     => 'automatizacion-ia',
    ],
];
